#!/usr/bin/ruby

require 'socket'

def start_with_socket(stream, cmd)

  server = TCPServer.new(stream)

  Thread.new do
    IO.select([server])
    pid = fork do
      env = {}
      env['LISTEN_PID'] = $$.to_s
      env['LISTEN_FDS'] = 1.to_s
      Process.setsid()
      exec(env, *cmd, 3 => server)
    end
  end

end

start_with_socket(2000, './daemon')
sleep
